### ISSUE TITLE
Documentation for BaseFormatter methods

### ISSUE THREAD

**Issue by expectocode** [expectocode/telegram-export#16]
It's not very friendly to require Formatter writers to read the BaseFormatter methods. We should generate some docs, even if only to display name and docstring.

**Comment by expectocode** [comment]
Something that people can use to list methods and their descriptions is `python3 -m pydoc formatters/baseformatter.py`. It works decently for now.

**Comment by Lonami** [comment]
Oh, `pydoc` is cool, but sure something like `readthedocs` would be even more friendly.

> It's not very friendly to require Formatter writers to read the BaseFormatter methods.

That's silly, though. If you're going to develop for a library you definitely should know at least the method definitions, and since this isn't aimed at end users (rather, other programmers), it's not that much of an issue. Once a few formatters are ready anyway I doubt anyone has the need for more and if they do any technical user wouldn't mind reading the definitions or starting from another formatter that's already implemented if they were to write a new one.

**Comment by expectocode** [comment]
True. I think pydoc and personal conversations should suffice for our purposes.

**Comment by Lonami** [comment]
*Closing issues without writing any code 101.*
