### ISSUE TITLE
strategy to download

### ISSUE THREAD

**Issue by nobody16** [expectocode/telegram-export#31]
Just to know, what's the strategy to download/resume files?
ie, you are downloading, hit ^C, and run again. It will re-download all of the files? without any skip?

What happen if the same file exists? I see in the documentation will be re-download/overwriten, but it's not better to have .1 or .2 files? or skip, just to continue downloading from the previous execution maybe using some config setting.

I'm in a channel with tons of huge files, if something wrong happend, I need to restart again and then download everything again. Imho, don't have sense.

**Comment by Lonami** [comment]
If a file exists, it won't be redownloaded. They are not overwriten, but this only applies **when `download_past_media` is called**. That is, if you're going through the entire message history and some media (due to your media format string) happens to result in the same username, it will be overwritten (and that's why you need to choose a good format string, default guarantees there won't be the same name for two files).

**Comment by expectocode** [comment]
The strategy is this: 
When downloading is interrupted, the half-saved file is deleted, and the current backlog of unsaved files is stored in the DB.

However, this is not quite fully implemented yet - half-saved files aren't deleted.

**Comment by expectocode** [comment]
By the way, if you just want to ask us a question like this, I suggest you use t.me/expectocode rather than opening an issue.
